/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotpRouteImport } from './routes/totp'
import { Route as StatusRouteImport } from './routes/status'
import { Route as Reset_passwordRouteImport } from './routes/reset_password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Forgot_passwordRouteImport } from './routes/forgot_password'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTenantsRouteImport } from './routes/admin/tenants'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminKeysRouteImport } from './routes/admin/keys'
import { Route as AdminGroupsRouteImport } from './routes/admin/groups'
import { Route as AdminConsentsRouteImport } from './routes/admin/consents'
import { Route as AdminAuthorizationDetailTypesRouteImport } from './routes/admin/authorization-detail-types'
import { Route as AdminAudit_eventsRouteImport } from './routes/admin/audit_events'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AdminAgentsRouteImport } from './routes/admin/agents'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountPasswordRouteImport } from './routes/account/password'
import { Route as AccountEmailsRouteImport } from './routes/account/emails'
import { Route as AccountDataRouteImport } from './routes/account/data'
import { Route as AccountAppsRouteImport } from './routes/account/apps'
import { Route as AccountApplicationsRouteImport } from './routes/account/applications'
import { Route as AccountActivityRouteImport } from './routes/account/activity'
import { Route as AdminUsersSubRouteImport } from './routes/admin/users_/$sub'
import { Route as AdminTenantAttributesRouteImport } from './routes/admin/tenant/attributes'
import { Route as AdminRolesNameRouteImport } from './routes/admin/roles_/$name'
import { Route as AdminGroupsGroupIdRouteImport } from './routes/admin/groups_/$groupId'
import { Route as AdminFederationEntraRouteImport } from './routes/admin/federation/entra'
import { Route as AdminApplicationsApplicationIdRouteImport } from './routes/admin/applications_/$applicationId'
import { Route as AdminAgentsAgentIdRouteImport } from './routes/admin/agents_/$agentId'
import { Route as AccountEmailVerifyRouteImport } from './routes/account/email/verify'
import { Route as AdminApplicationsApplicationIdIndexRouteImport } from './routes/admin/applications_/$applicationId.index'
import { Route as AdminApplicationsApplicationIdEditRouteImport } from './routes/admin/applications_/$applicationId.edit'

const TotpRoute = TotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const Reset_passwordRoute = Reset_passwordRouteImport.update({
  id: '/reset_password',
  path: '/reset_password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Forgot_passwordRoute = Forgot_passwordRouteImport.update({
  id: '/forgot_password',
  path: '/forgot_password',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKeysRoute = AdminKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConsentsRoute = AdminConsentsRouteImport.update({
  id: '/consents',
  path: '/consents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuthorizationDetailTypesRoute =
  AdminAuthorizationDetailTypesRouteImport.update({
    id: '/authorization-detail-types',
    path: '/authorization-detail-types',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAudit_eventsRoute = AdminAudit_eventsRouteImport.update({
  id: '/audit_events',
  path: '/audit_events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountPasswordRoute = AccountPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountEmailsRoute = AccountEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountDataRoute = AccountDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountAppsRoute = AccountAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountApplicationsRoute = AccountApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountActivityRoute = AccountActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminUsersSubRoute = AdminUsersSubRouteImport.update({
  id: '/users_/$sub',
  path: '/users/$sub',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTenantAttributesRoute = AdminTenantAttributesRouteImport.update({
  id: '/tenant/attributes',
  path: '/tenant/attributes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesNameRoute = AdminRolesNameRouteImport.update({
  id: '/roles_/$name',
  path: '/roles/$name',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGroupsGroupIdRoute = AdminGroupsGroupIdRouteImport.update({
  id: '/groups_/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFederationEntraRoute = AdminFederationEntraRouteImport.update({
  id: '/federation/entra',
  path: '/federation/entra',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicationsApplicationIdRoute =
  AdminApplicationsApplicationIdRouteImport.update({
    id: '/applications_/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAgentsAgentIdRoute = AdminAgentsAgentIdRouteImport.update({
  id: '/agents_/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountEmailVerifyRoute = AccountEmailVerifyRouteImport.update({
  id: '/email/verify',
  path: '/email/verify',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminApplicationsApplicationIdIndexRoute =
  AdminApplicationsApplicationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminApplicationsApplicationIdRoute,
  } as any)
const AdminApplicationsApplicationIdEditRoute =
  AdminApplicationsApplicationIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminApplicationsApplicationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/forgot_password': typeof Forgot_passwordRoute
  '/login': typeof LoginRoute
  '/reset_password': typeof Reset_passwordRoute
  '/status': typeof StatusRoute
  '/totp': typeof TotpRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/applications': typeof AccountApplicationsRoute
  '/account/apps': typeof AccountAppsRoute
  '/account/data': typeof AccountDataRoute
  '/account/emails': typeof AccountEmailsRoute
  '/account/password': typeof AccountPasswordRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit_events': typeof AdminAudit_eventsRoute
  '/admin/authorization-detail-types': typeof AdminAuthorizationDetailTypesRoute
  '/admin/consents': typeof AdminConsentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/email/verify': typeof AccountEmailVerifyRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRouteWithChildren
  '/admin/federation/entra': typeof AdminFederationEntraRoute
  '/admin/groups/$groupId': typeof AdminGroupsGroupIdRoute
  '/admin/roles/$name': typeof AdminRolesNameRoute
  '/admin/tenant/attributes': typeof AdminTenantAttributesRoute
  '/admin/users/$sub': typeof AdminUsersSubRoute
  '/admin/applications/$applicationId/edit': typeof AdminApplicationsApplicationIdEditRoute
  '/admin/applications/$applicationId/': typeof AdminApplicationsApplicationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/forgot_password': typeof Forgot_passwordRoute
  '/login': typeof LoginRoute
  '/reset_password': typeof Reset_passwordRoute
  '/status': typeof StatusRoute
  '/totp': typeof TotpRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/applications': typeof AccountApplicationsRoute
  '/account/apps': typeof AccountAppsRoute
  '/account/data': typeof AccountDataRoute
  '/account/emails': typeof AccountEmailsRoute
  '/account/password': typeof AccountPasswordRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit_events': typeof AdminAudit_eventsRoute
  '/admin/authorization-detail-types': typeof AdminAuthorizationDetailTypesRoute
  '/admin/consents': typeof AdminConsentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/email/verify': typeof AccountEmailVerifyRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/federation/entra': typeof AdminFederationEntraRoute
  '/admin/groups/$groupId': typeof AdminGroupsGroupIdRoute
  '/admin/roles/$name': typeof AdminRolesNameRoute
  '/admin/tenant/attributes': typeof AdminTenantAttributesRoute
  '/admin/users/$sub': typeof AdminUsersSubRoute
  '/admin/applications/$applicationId/edit': typeof AdminApplicationsApplicationIdEditRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/forgot_password': typeof Forgot_passwordRoute
  '/login': typeof LoginRoute
  '/reset_password': typeof Reset_passwordRoute
  '/status': typeof StatusRoute
  '/totp': typeof TotpRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/applications': typeof AccountApplicationsRoute
  '/account/apps': typeof AccountAppsRoute
  '/account/data': typeof AccountDataRoute
  '/account/emails': typeof AccountEmailsRoute
  '/account/password': typeof AccountPasswordRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit_events': typeof AdminAudit_eventsRoute
  '/admin/authorization-detail-types': typeof AdminAuthorizationDetailTypesRoute
  '/admin/consents': typeof AdminConsentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/email/verify': typeof AccountEmailVerifyRoute
  '/admin/agents_/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/applications_/$applicationId': typeof AdminApplicationsApplicationIdRouteWithChildren
  '/admin/federation/entra': typeof AdminFederationEntraRoute
  '/admin/groups_/$groupId': typeof AdminGroupsGroupIdRoute
  '/admin/roles_/$name': typeof AdminRolesNameRoute
  '/admin/tenant/attributes': typeof AdminTenantAttributesRoute
  '/admin/users_/$sub': typeof AdminUsersSubRoute
  '/admin/applications_/$applicationId/edit': typeof AdminApplicationsApplicationIdEditRoute
  '/admin/applications_/$applicationId/': typeof AdminApplicationsApplicationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/callback'
    | '/consent'
    | '/device'
    | '/forgot_password'
    | '/login'
    | '/reset_password'
    | '/status'
    | '/totp'
    | '/account/activity'
    | '/account/applications'
    | '/account/apps'
    | '/account/data'
    | '/account/emails'
    | '/account/password'
    | '/account/profile'
    | '/account/security'
    | '/admin/agents'
    | '/admin/applications'
    | '/admin/audit_events'
    | '/admin/authorization-detail-types'
    | '/admin/consents'
    | '/admin/groups'
    | '/admin/keys'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/users'
    | '/account/'
    | '/admin/'
    | '/account/email/verify'
    | '/admin/agents/$agentId'
    | '/admin/applications/$applicationId'
    | '/admin/federation/entra'
    | '/admin/groups/$groupId'
    | '/admin/roles/$name'
    | '/admin/tenant/attributes'
    | '/admin/users/$sub'
    | '/admin/applications/$applicationId/edit'
    | '/admin/applications/$applicationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/consent'
    | '/device'
    | '/forgot_password'
    | '/login'
    | '/reset_password'
    | '/status'
    | '/totp'
    | '/account/activity'
    | '/account/applications'
    | '/account/apps'
    | '/account/data'
    | '/account/emails'
    | '/account/password'
    | '/account/profile'
    | '/account/security'
    | '/admin/agents'
    | '/admin/applications'
    | '/admin/audit_events'
    | '/admin/authorization-detail-types'
    | '/admin/consents'
    | '/admin/groups'
    | '/admin/keys'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/users'
    | '/account'
    | '/admin'
    | '/account/email/verify'
    | '/admin/agents/$agentId'
    | '/admin/federation/entra'
    | '/admin/groups/$groupId'
    | '/admin/roles/$name'
    | '/admin/tenant/attributes'
    | '/admin/users/$sub'
    | '/admin/applications/$applicationId/edit'
    | '/admin/applications/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/callback'
    | '/consent'
    | '/device'
    | '/forgot_password'
    | '/login'
    | '/reset_password'
    | '/status'
    | '/totp'
    | '/account/activity'
    | '/account/applications'
    | '/account/apps'
    | '/account/data'
    | '/account/emails'
    | '/account/password'
    | '/account/profile'
    | '/account/security'
    | '/admin/agents'
    | '/admin/applications'
    | '/admin/audit_events'
    | '/admin/authorization-detail-types'
    | '/admin/consents'
    | '/admin/groups'
    | '/admin/keys'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/users'
    | '/account/'
    | '/admin/'
    | '/account/email/verify'
    | '/admin/agents_/$agentId'
    | '/admin/applications_/$applicationId'
    | '/admin/federation/entra'
    | '/admin/groups_/$groupId'
    | '/admin/roles_/$name'
    | '/admin/tenant/attributes'
    | '/admin/users_/$sub'
    | '/admin/applications_/$applicationId/edit'
    | '/admin/applications_/$applicationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  ConsentRoute: typeof ConsentRoute
  DeviceRoute: typeof DeviceRoute
  Forgot_passwordRoute: typeof Forgot_passwordRoute
  LoginRoute: typeof LoginRoute
  Reset_passwordRoute: typeof Reset_passwordRoute
  StatusRoute: typeof StatusRoute
  TotpRoute: typeof TotpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/totp': {
      id: '/totp'
      path: '/totp'
      fullPath: '/totp'
      preLoaderRoute: typeof TotpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset_password': {
      id: '/reset_password'
      path: '/reset_password'
      fullPath: '/reset_password'
      preLoaderRoute: typeof Reset_passwordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot_password': {
      id: '/forgot_password'
      path: '/forgot_password'
      fullPath: '/forgot_password'
      preLoaderRoute: typeof Forgot_passwordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/keys': {
      id: '/admin/keys'
      path: '/keys'
      fullPath: '/admin/keys'
      preLoaderRoute: typeof AdminKeysRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/consents': {
      id: '/admin/consents'
      path: '/consents'
      fullPath: '/admin/consents'
      preLoaderRoute: typeof AdminConsentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/authorization-detail-types': {
      id: '/admin/authorization-detail-types'
      path: '/authorization-detail-types'
      fullPath: '/admin/authorization-detail-types'
      preLoaderRoute: typeof AdminAuthorizationDetailTypesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit_events': {
      id: '/admin/audit_events'
      path: '/audit_events'
      fullPath: '/admin/audit_events'
      preLoaderRoute: typeof AdminAudit_eventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/password': {
      id: '/account/password'
      path: '/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AccountPasswordRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/emails': {
      id: '/account/emails'
      path: '/emails'
      fullPath: '/account/emails'
      preLoaderRoute: typeof AccountEmailsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/data': {
      id: '/account/data'
      path: '/data'
      fullPath: '/account/data'
      preLoaderRoute: typeof AccountDataRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/apps': {
      id: '/account/apps'
      path: '/apps'
      fullPath: '/account/apps'
      preLoaderRoute: typeof AccountAppsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/applications': {
      id: '/account/applications'
      path: '/applications'
      fullPath: '/account/applications'
      preLoaderRoute: typeof AccountApplicationsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/activity': {
      id: '/account/activity'
      path: '/activity'
      fullPath: '/account/activity'
      preLoaderRoute: typeof AccountActivityRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/users_/$sub': {
      id: '/admin/users_/$sub'
      path: '/users/$sub'
      fullPath: '/admin/users/$sub'
      preLoaderRoute: typeof AdminUsersSubRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tenant/attributes': {
      id: '/admin/tenant/attributes'
      path: '/tenant/attributes'
      fullPath: '/admin/tenant/attributes'
      preLoaderRoute: typeof AdminTenantAttributesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles_/$name': {
      id: '/admin/roles_/$name'
      path: '/roles/$name'
      fullPath: '/admin/roles/$name'
      preLoaderRoute: typeof AdminRolesNameRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/groups_/$groupId': {
      id: '/admin/groups_/$groupId'
      path: '/groups/$groupId'
      fullPath: '/admin/groups/$groupId'
      preLoaderRoute: typeof AdminGroupsGroupIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/federation/entra': {
      id: '/admin/federation/entra'
      path: '/federation/entra'
      fullPath: '/admin/federation/entra'
      preLoaderRoute: typeof AdminFederationEntraRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applications_/$applicationId': {
      id: '/admin/applications_/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/admin/applications/$applicationId'
      preLoaderRoute: typeof AdminApplicationsApplicationIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/agents_/$agentId': {
      id: '/admin/agents_/$agentId'
      path: '/agents/$agentId'
      fullPath: '/admin/agents/$agentId'
      preLoaderRoute: typeof AdminAgentsAgentIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/email/verify': {
      id: '/account/email/verify'
      path: '/email/verify'
      fullPath: '/account/email/verify'
      preLoaderRoute: typeof AccountEmailVerifyRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/applications_/$applicationId/': {
      id: '/admin/applications_/$applicationId/'
      path: '/'
      fullPath: '/admin/applications/$applicationId/'
      preLoaderRoute: typeof AdminApplicationsApplicationIdIndexRouteImport
      parentRoute: typeof AdminApplicationsApplicationIdRoute
    }
    '/admin/applications_/$applicationId/edit': {
      id: '/admin/applications_/$applicationId/edit'
      path: '/edit'
      fullPath: '/admin/applications/$applicationId/edit'
      preLoaderRoute: typeof AdminApplicationsApplicationIdEditRouteImport
      parentRoute: typeof AdminApplicationsApplicationIdRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountActivityRoute: typeof AccountActivityRoute
  AccountApplicationsRoute: typeof AccountApplicationsRoute
  AccountAppsRoute: typeof AccountAppsRoute
  AccountDataRoute: typeof AccountDataRoute
  AccountEmailsRoute: typeof AccountEmailsRoute
  AccountPasswordRoute: typeof AccountPasswordRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountEmailVerifyRoute: typeof AccountEmailVerifyRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountActivityRoute: AccountActivityRoute,
  AccountApplicationsRoute: AccountApplicationsRoute,
  AccountAppsRoute: AccountAppsRoute,
  AccountDataRoute: AccountDataRoute,
  AccountEmailsRoute: AccountEmailsRoute,
  AccountPasswordRoute: AccountPasswordRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountEmailVerifyRoute: AccountEmailVerifyRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminApplicationsApplicationIdRouteChildren {
  AdminApplicationsApplicationIdEditRoute: typeof AdminApplicationsApplicationIdEditRoute
  AdminApplicationsApplicationIdIndexRoute: typeof AdminApplicationsApplicationIdIndexRoute
}

const AdminApplicationsApplicationIdRouteChildren: AdminApplicationsApplicationIdRouteChildren =
  {
    AdminApplicationsApplicationIdEditRoute:
      AdminApplicationsApplicationIdEditRoute,
    AdminApplicationsApplicationIdIndexRoute:
      AdminApplicationsApplicationIdIndexRoute,
  }

const AdminApplicationsApplicationIdRouteWithChildren =
  AdminApplicationsApplicationIdRoute._addFileChildren(
    AdminApplicationsApplicationIdRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAudit_eventsRoute: typeof AdminAudit_eventsRoute
  AdminAuthorizationDetailTypesRoute: typeof AdminAuthorizationDetailTypesRoute
  AdminConsentsRoute: typeof AdminConsentsRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminKeysRoute: typeof AdminKeysRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAgentsAgentIdRoute: typeof AdminAgentsAgentIdRoute
  AdminApplicationsApplicationIdRoute: typeof AdminApplicationsApplicationIdRouteWithChildren
  AdminFederationEntraRoute: typeof AdminFederationEntraRoute
  AdminGroupsGroupIdRoute: typeof AdminGroupsGroupIdRoute
  AdminRolesNameRoute: typeof AdminRolesNameRoute
  AdminTenantAttributesRoute: typeof AdminTenantAttributesRoute
  AdminUsersSubRoute: typeof AdminUsersSubRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAudit_eventsRoute: AdminAudit_eventsRoute,
  AdminAuthorizationDetailTypesRoute: AdminAuthorizationDetailTypesRoute,
  AdminConsentsRoute: AdminConsentsRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminKeysRoute: AdminKeysRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAgentsAgentIdRoute: AdminAgentsAgentIdRoute,
  AdminApplicationsApplicationIdRoute:
    AdminApplicationsApplicationIdRouteWithChildren,
  AdminFederationEntraRoute: AdminFederationEntraRoute,
  AdminGroupsGroupIdRoute: AdminGroupsGroupIdRoute,
  AdminRolesNameRoute: AdminRolesNameRoute,
  AdminTenantAttributesRoute: AdminTenantAttributesRoute,
  AdminUsersSubRoute: AdminUsersSubRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CallbackRoute: CallbackRoute,
  ConsentRoute: ConsentRoute,
  DeviceRoute: DeviceRoute,
  Forgot_passwordRoute: Forgot_passwordRoute,
  LoginRoute: LoginRoute,
  Reset_passwordRoute: Reset_passwordRoute,
  StatusRoute: StatusRoute,
  TotpRoute: TotpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
