/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotpRouteImport } from './routes/totp'
import { Route as StatusRouteImport } from './routes/status'
import { Route as Reset_passwordRouteImport } from './routes/reset_password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Forgot_passwordRouteImport } from './routes/forgot_password'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminKeysRouteImport } from './routes/admin.keys'
import { Route as AdminGroupsRouteImport } from './routes/admin.groups'
import { Route as AdminConsentsRouteImport } from './routes/admin.consents'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminAuthorizationDetailTypesRouteImport } from './routes/admin.authorization-detail-types'
import { Route as AdminAudit_eventsRouteImport } from './routes/admin.audit_events'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountPasswordRouteImport } from './routes/account.password'
import { Route as AccountEmailsRouteImport } from './routes/account.emails'
import { Route as AccountDataRouteImport } from './routes/account.data'
import { Route as AccountAppsRouteImport } from './routes/account.apps'
import { Route as AccountApplicationsRouteImport } from './routes/account.applications'
import { Route as AccountActivityRouteImport } from './routes/account.activity'
import { Route as AdminWsfedRelyingPartiesRouteImport } from './routes/admin.wsfed.relying-parties'
import { Route as AdminUsersSubRouteImport } from './routes/admin.users_.$sub'
import { Route as AdminTenantAttributesRouteImport } from './routes/admin.tenant.attributes'
import { Route as AdminRolesNameRouteImport } from './routes/admin.roles_.$name'
import { Route as AdminGroupsGroupIdRouteImport } from './routes/admin.groups_.$groupId'
import { Route as AdminClientsClientIdRouteImport } from './routes/admin.clients_.$clientId'
import { Route as AdminAgentsAgentIdRouteImport } from './routes/admin.agents_.$agentId'
import { Route as AccountEmailVerifyRouteImport } from './routes/account.email.verify'

const TotpRoute = TotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const Reset_passwordRoute = Reset_passwordRouteImport.update({
  id: '/reset_password',
  path: '/reset_password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Forgot_passwordRoute = Forgot_passwordRouteImport.update({
  id: '/forgot_password',
  path: '/forgot_password',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKeysRoute = AdminKeysRouteImport.update({
  id: '/admin/keys',
  path: '/admin/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/admin/groups',
  path: '/admin/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsentsRoute = AdminConsentsRouteImport.update({
  id: '/admin/consents',
  path: '/admin/consents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthorizationDetailTypesRoute =
  AdminAuthorizationDetailTypesRouteImport.update({
    id: '/admin/authorization-detail-types',
    path: '/admin/authorization-detail-types',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAudit_eventsRoute = AdminAudit_eventsRouteImport.update({
  id: '/admin/audit_events',
  path: '/admin/audit_events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPasswordRoute = AccountPasswordRouteImport.update({
  id: '/account/password',
  path: '/account/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountEmailsRoute = AccountEmailsRouteImport.update({
  id: '/account/emails',
  path: '/account/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDataRoute = AccountDataRouteImport.update({
  id: '/account/data',
  path: '/account/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAppsRoute = AccountAppsRouteImport.update({
  id: '/account/apps',
  path: '/account/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountApplicationsRoute = AccountApplicationsRouteImport.update({
  id: '/account/applications',
  path: '/account/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountActivityRoute = AccountActivityRouteImport.update({
  id: '/account/activity',
  path: '/account/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWsfedRelyingPartiesRoute =
  AdminWsfedRelyingPartiesRouteImport.update({
    id: '/admin/wsfed/relying-parties',
    path: '/admin/wsfed/relying-parties',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersSubRoute = AdminUsersSubRouteImport.update({
  id: '/admin/users_/$sub',
  path: '/admin/users/$sub',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantAttributesRoute = AdminTenantAttributesRouteImport.update({
  id: '/admin/tenant/attributes',
  path: '/admin/tenant/attributes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesNameRoute = AdminRolesNameRouteImport.update({
  id: '/admin/roles_/$name',
  path: '/admin/roles/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGroupsGroupIdRoute = AdminGroupsGroupIdRouteImport.update({
  id: '/admin/groups_/$groupId',
  path: '/admin/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsClientIdRoute = AdminClientsClientIdRouteImport.update({
  id: '/admin/clients_/$clientId',
  path: '/admin/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsAgentIdRoute = AdminAgentsAgentIdRouteImport.update({
  id: '/admin/agents_/$agentId',
  path: '/admin/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountEmailVerifyRoute = AccountEmailVerifyRouteImport.update({
  id: '/account/email/verify',
  path: '/account/email/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/forgot_password': typeof Forgot_passwordRoute
  '/login': typeof LoginRoute
  '/reset_password': typeof Reset_passwordRoute
  '/status': typeof StatusRoute
  '/totp': typeof TotpRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/applications': typeof AccountApplicationsRoute
  '/account/apps': typeof AccountAppsRoute
  '/account/data': typeof AccountDataRoute
  '/account/emails': typeof AccountEmailsRoute
  '/account/password': typeof AccountPasswordRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit_events': typeof AdminAudit_eventsRoute
  '/admin/authorization-detail-types': typeof AdminAuthorizationDetailTypesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/consents': typeof AdminConsentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/email/verify': typeof AccountEmailVerifyRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/groups/$groupId': typeof AdminGroupsGroupIdRoute
  '/admin/roles/$name': typeof AdminRolesNameRoute
  '/admin/tenant/attributes': typeof AdminTenantAttributesRoute
  '/admin/users/$sub': typeof AdminUsersSubRoute
  '/admin/wsfed/relying-parties': typeof AdminWsfedRelyingPartiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/forgot_password': typeof Forgot_passwordRoute
  '/login': typeof LoginRoute
  '/reset_password': typeof Reset_passwordRoute
  '/status': typeof StatusRoute
  '/totp': typeof TotpRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/applications': typeof AccountApplicationsRoute
  '/account/apps': typeof AccountAppsRoute
  '/account/data': typeof AccountDataRoute
  '/account/emails': typeof AccountEmailsRoute
  '/account/password': typeof AccountPasswordRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit_events': typeof AdminAudit_eventsRoute
  '/admin/authorization-detail-types': typeof AdminAuthorizationDetailTypesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/consents': typeof AdminConsentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/email/verify': typeof AccountEmailVerifyRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/clients/$clientId': typeof AdminClientsClientIdRoute
  '/admin/groups/$groupId': typeof AdminGroupsGroupIdRoute
  '/admin/roles/$name': typeof AdminRolesNameRoute
  '/admin/tenant/attributes': typeof AdminTenantAttributesRoute
  '/admin/users/$sub': typeof AdminUsersSubRoute
  '/admin/wsfed/relying-parties': typeof AdminWsfedRelyingPartiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/forgot_password': typeof Forgot_passwordRoute
  '/login': typeof LoginRoute
  '/reset_password': typeof Reset_passwordRoute
  '/status': typeof StatusRoute
  '/totp': typeof TotpRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/applications': typeof AccountApplicationsRoute
  '/account/apps': typeof AccountAppsRoute
  '/account/data': typeof AccountDataRoute
  '/account/emails': typeof AccountEmailsRoute
  '/account/password': typeof AccountPasswordRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit_events': typeof AdminAudit_eventsRoute
  '/admin/authorization-detail-types': typeof AdminAuthorizationDetailTypesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/consents': typeof AdminConsentsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/email/verify': typeof AccountEmailVerifyRoute
  '/admin/agents_/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/clients_/$clientId': typeof AdminClientsClientIdRoute
  '/admin/groups_/$groupId': typeof AdminGroupsGroupIdRoute
  '/admin/roles_/$name': typeof AdminRolesNameRoute
  '/admin/tenant/attributes': typeof AdminTenantAttributesRoute
  '/admin/users_/$sub': typeof AdminUsersSubRoute
  '/admin/wsfed/relying-parties': typeof AdminWsfedRelyingPartiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/consent'
    | '/device'
    | '/forgot_password'
    | '/login'
    | '/reset_password'
    | '/status'
    | '/totp'
    | '/account/activity'
    | '/account/applications'
    | '/account/apps'
    | '/account/data'
    | '/account/emails'
    | '/account/password'
    | '/account/profile'
    | '/account/security'
    | '/admin/agents'
    | '/admin/applications'
    | '/admin/audit_events'
    | '/admin/authorization-detail-types'
    | '/admin/clients'
    | '/admin/consents'
    | '/admin/groups'
    | '/admin/keys'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/users'
    | '/account/'
    | '/admin/'
    | '/account/email/verify'
    | '/admin/agents/$agentId'
    | '/admin/clients/$clientId'
    | '/admin/groups/$groupId'
    | '/admin/roles/$name'
    | '/admin/tenant/attributes'
    | '/admin/users/$sub'
    | '/admin/wsfed/relying-parties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/consent'
    | '/device'
    | '/forgot_password'
    | '/login'
    | '/reset_password'
    | '/status'
    | '/totp'
    | '/account/activity'
    | '/account/applications'
    | '/account/apps'
    | '/account/data'
    | '/account/emails'
    | '/account/password'
    | '/account/profile'
    | '/account/security'
    | '/admin/agents'
    | '/admin/applications'
    | '/admin/audit_events'
    | '/admin/authorization-detail-types'
    | '/admin/clients'
    | '/admin/consents'
    | '/admin/groups'
    | '/admin/keys'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/users'
    | '/account'
    | '/admin'
    | '/account/email/verify'
    | '/admin/agents/$agentId'
    | '/admin/clients/$clientId'
    | '/admin/groups/$groupId'
    | '/admin/roles/$name'
    | '/admin/tenant/attributes'
    | '/admin/users/$sub'
    | '/admin/wsfed/relying-parties'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/consent'
    | '/device'
    | '/forgot_password'
    | '/login'
    | '/reset_password'
    | '/status'
    | '/totp'
    | '/account/activity'
    | '/account/applications'
    | '/account/apps'
    | '/account/data'
    | '/account/emails'
    | '/account/password'
    | '/account/profile'
    | '/account/security'
    | '/admin/agents'
    | '/admin/applications'
    | '/admin/audit_events'
    | '/admin/authorization-detail-types'
    | '/admin/clients'
    | '/admin/consents'
    | '/admin/groups'
    | '/admin/keys'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/users'
    | '/account/'
    | '/admin/'
    | '/account/email/verify'
    | '/admin/agents_/$agentId'
    | '/admin/clients_/$clientId'
    | '/admin/groups_/$groupId'
    | '/admin/roles_/$name'
    | '/admin/tenant/attributes'
    | '/admin/users_/$sub'
    | '/admin/wsfed/relying-parties'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  ConsentRoute: typeof ConsentRoute
  DeviceRoute: typeof DeviceRoute
  Forgot_passwordRoute: typeof Forgot_passwordRoute
  LoginRoute: typeof LoginRoute
  Reset_passwordRoute: typeof Reset_passwordRoute
  StatusRoute: typeof StatusRoute
  TotpRoute: typeof TotpRoute
  AccountActivityRoute: typeof AccountActivityRoute
  AccountApplicationsRoute: typeof AccountApplicationsRoute
  AccountAppsRoute: typeof AccountAppsRoute
  AccountDataRoute: typeof AccountDataRoute
  AccountEmailsRoute: typeof AccountEmailsRoute
  AccountPasswordRoute: typeof AccountPasswordRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAudit_eventsRoute: typeof AdminAudit_eventsRoute
  AdminAuthorizationDetailTypesRoute: typeof AdminAuthorizationDetailTypesRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminConsentsRoute: typeof AdminConsentsRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminKeysRoute: typeof AdminKeysRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AccountEmailVerifyRoute: typeof AccountEmailVerifyRoute
  AdminAgentsAgentIdRoute: typeof AdminAgentsAgentIdRoute
  AdminClientsClientIdRoute: typeof AdminClientsClientIdRoute
  AdminGroupsGroupIdRoute: typeof AdminGroupsGroupIdRoute
  AdminRolesNameRoute: typeof AdminRolesNameRoute
  AdminTenantAttributesRoute: typeof AdminTenantAttributesRoute
  AdminUsersSubRoute: typeof AdminUsersSubRoute
  AdminWsfedRelyingPartiesRoute: typeof AdminWsfedRelyingPartiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/totp': {
      id: '/totp'
      path: '/totp'
      fullPath: '/totp'
      preLoaderRoute: typeof TotpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset_password': {
      id: '/reset_password'
      path: '/reset_password'
      fullPath: '/reset_password'
      preLoaderRoute: typeof Reset_passwordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot_password': {
      id: '/forgot_password'
      path: '/forgot_password'
      fullPath: '/forgot_password'
      preLoaderRoute: typeof Forgot_passwordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/keys': {
      id: '/admin/keys'
      path: '/admin/keys'
      fullPath: '/admin/keys'
      preLoaderRoute: typeof AdminKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/consents': {
      id: '/admin/consents'
      path: '/admin/consents'
      fullPath: '/admin/consents'
      preLoaderRoute: typeof AdminConsentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/authorization-detail-types': {
      id: '/admin/authorization-detail-types'
      path: '/admin/authorization-detail-types'
      fullPath: '/admin/authorization-detail-types'
      preLoaderRoute: typeof AdminAuthorizationDetailTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit_events': {
      id: '/admin/audit_events'
      path: '/admin/audit_events'
      fullPath: '/admin/audit_events'
      preLoaderRoute: typeof AdminAudit_eventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/security': {
      id: '/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/password': {
      id: '/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AccountPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/emails': {
      id: '/account/emails'
      path: '/account/emails'
      fullPath: '/account/emails'
      preLoaderRoute: typeof AccountEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/data': {
      id: '/account/data'
      path: '/account/data'
      fullPath: '/account/data'
      preLoaderRoute: typeof AccountDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/apps': {
      id: '/account/apps'
      path: '/account/apps'
      fullPath: '/account/apps'
      preLoaderRoute: typeof AccountAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/applications': {
      id: '/account/applications'
      path: '/account/applications'
      fullPath: '/account/applications'
      preLoaderRoute: typeof AccountApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/activity': {
      id: '/account/activity'
      path: '/account/activity'
      fullPath: '/account/activity'
      preLoaderRoute: typeof AccountActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wsfed/relying-parties': {
      id: '/admin/wsfed/relying-parties'
      path: '/admin/wsfed/relying-parties'
      fullPath: '/admin/wsfed/relying-parties'
      preLoaderRoute: typeof AdminWsfedRelyingPartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users_/$sub': {
      id: '/admin/users_/$sub'
      path: '/admin/users/$sub'
      fullPath: '/admin/users/$sub'
      preLoaderRoute: typeof AdminUsersSubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenant/attributes': {
      id: '/admin/tenant/attributes'
      path: '/admin/tenant/attributes'
      fullPath: '/admin/tenant/attributes'
      preLoaderRoute: typeof AdminTenantAttributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles_/$name': {
      id: '/admin/roles_/$name'
      path: '/admin/roles/$name'
      fullPath: '/admin/roles/$name'
      preLoaderRoute: typeof AdminRolesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/groups_/$groupId': {
      id: '/admin/groups_/$groupId'
      path: '/admin/groups/$groupId'
      fullPath: '/admin/groups/$groupId'
      preLoaderRoute: typeof AdminGroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients_/$clientId': {
      id: '/admin/clients_/$clientId'
      path: '/admin/clients/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AdminClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents_/$agentId': {
      id: '/admin/agents_/$agentId'
      path: '/admin/agents/$agentId'
      fullPath: '/admin/agents/$agentId'
      preLoaderRoute: typeof AdminAgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/email/verify': {
      id: '/account/email/verify'
      path: '/account/email/verify'
      fullPath: '/account/email/verify'
      preLoaderRoute: typeof AccountEmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  ConsentRoute: ConsentRoute,
  DeviceRoute: DeviceRoute,
  Forgot_passwordRoute: Forgot_passwordRoute,
  LoginRoute: LoginRoute,
  Reset_passwordRoute: Reset_passwordRoute,
  StatusRoute: StatusRoute,
  TotpRoute: TotpRoute,
  AccountActivityRoute: AccountActivityRoute,
  AccountApplicationsRoute: AccountApplicationsRoute,
  AccountAppsRoute: AccountAppsRoute,
  AccountDataRoute: AccountDataRoute,
  AccountEmailsRoute: AccountEmailsRoute,
  AccountPasswordRoute: AccountPasswordRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAudit_eventsRoute: AdminAudit_eventsRoute,
  AdminAuthorizationDetailTypesRoute: AdminAuthorizationDetailTypesRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminConsentsRoute: AdminConsentsRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminKeysRoute: AdminKeysRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AccountEmailVerifyRoute: AccountEmailVerifyRoute,
  AdminAgentsAgentIdRoute: AdminAgentsAgentIdRoute,
  AdminClientsClientIdRoute: AdminClientsClientIdRoute,
  AdminGroupsGroupIdRoute: AdminGroupsGroupIdRoute,
  AdminRolesNameRoute: AdminRolesNameRoute,
  AdminTenantAttributesRoute: AdminTenantAttributesRoute,
  AdminUsersSubRoute: AdminUsersSubRoute,
  AdminWsfedRelyingPartiesRoute: AdminWsfedRelyingPartiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
