/**
 * Layer 4 — テスト用 mTLS 証明書フィクスチャ。
 *
 * P-256 自己署名証明書を 2 つ用意し、parse/thumbprint/binding テストで使う。
 * openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 -nodes ... で生成。
 * 有効期限は 100 年超で、テストの時計と独立。
 */

export const TEST_CERT_PEM = `-----BEGIN CERTIFICATE-----
MIIBoTCCAUegAwIBAgIUVK9eP5Vwn6G4kZ5yV+5i1RZOop0wCgYIKoZIzj0EAwIw
JTERMA8GA1UEAwwIbXRscy1hcHAxEDAOBgNVBAoMB0V4YW1wbGUwIBcNMjYwNjA3
MDMwODAxWhgPMjEyNjA1MTQwMzA4MDFaMCUxETAPBgNVBAMMCG10bHMtYXBwMRAw
DgYDVQQKDAdFeGFtcGxlMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXI+p7M53
5fLjKs28JQciAFAGm6Q7abwFcfC32cFHnUZprNTJhIjp8zrGbG0c4wfQcLY5Fpbo
YN8x4HMNVEyKAKNTMFEwHQYDVR0OBBYEFLIlcP+pbO3czs0GexzMtci/4YMmMB8G
A1UdIwQYMBaAFLIlcP+pbO3czs0GexzMtci/4YMmMA8GA1UdEwEB/wQFMAMBAf8w
CgYIKoZIzj0EAwIDSAAwRQIhAOn1hFnVEPbxaerRmu79gDrYm5Ii1q+6UFukMb1i
l2VCAiAkXtJdfb0prDymOy7CzK3FeiGteoRhMocBc61Mon0HXQ==
-----END CERTIFICATE-----
`

export const TEST_CERT_OTHER_PEM = `-----BEGIN CERTIFICATE-----
MIIBgDCCASWgAwIBAgIUK3hMLGBORrb68nO2arUsgLWWdrQwCgYIKoZIzj0EAwIw
FDESMBAGA1UEAwwJb3RoZXItYXBwMCAXDTI2MDYwNzAzMDgwMVoYDzIxMjYwNTE0
MDMwODAxWjAUMRIwEAYDVQQDDAlvdGhlci1hcHAwWTATBgcqhkjOPQIBBggqhkjO
PQMBBwNCAASB/Aj4vCIz5ExTjSmkfNzni3bkhpMhc5uzdVQSAflxXXafI7y0r3sa
+Amlpmcz5DB6QEJ+EhVs3rGm8myF6jeUo1MwUTAdBgNVHQ4EFgQUBt7HxikKODIB
drBBZxGbjWA/OA0wHwYDVR0jBBgwFoAUBt7HxikKODIBdrBBZxGbjWA/OA0wDwYD
VR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNJADBGAiEA2H4x2/pmoAgqNrLEhelA
xh4WQ4foc+EfEzsUVqP5zgkCIQCLRvXkfRCj2P1HTcm2KBAQ0E69ZUmEXlWQkTlF
73iIxA==
-----END CERTIFICATE-----
`

/** TEST_CERT_PEM の subject DN (RFC 4514 形式)。 */
export const TEST_CERT_SUBJECT_DN = 'CN=mtls-app,O=Example'
