apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: oauth2-idp

resources:
  - deployment.yaml
  - service.yaml
  - scaling.yaml
  - network-policy.yaml
  - service-monitor.yaml
  - key-rotation-cronjob.yaml
